FROM apache/airflow:2.9.0

USER root

# Install build tools and PostgreSQL development libraries
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libstdc++6 \
    ca-certificates \
    libstdc++-12-dev \
    g++ \
    make \
    libpq-dev \
    libssl-dev \
    libkrb5-dev \
    libldap2-dev \
 && rm -rf /var/lib/apt/lists/*
# Install Python PostgreSQL driver

# restore non-root user used by the base image
USER airflow
RUN pip install --no-cache-dir psycopg2-binary